import React, { createContext, useContext, useState, useEffect } from 'react';

import { StorageService } from '../services/storageService';

export type Language = 'en' | 'hi' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'header.title': 'NabhaCare',
    'header.subtitle': 'Nabha Rural Care',
    'header.home': 'Home',
    'header.problem': 'Problem',
    'header.solution': 'Solution',
    'header.servicearea': 'Service Area',
    'header.impact': 'Impact',
    'header.signin': 'Sign In',
    'header.language': 'Language',
    
    // Hero Section
    'hero.location': 'Nabha, Punjab',
    'hero.title': 'Bridging Healthcare',
    'hero.subtitle': 'to Rural Punjab',
    'hero.description': 'Connecting 173 villages to quality healthcare through telemedicine, digital health records, and AI-powered medical assistance designed for rural India.',
    'hero.learnMore': 'Learn More',
    'hero.contactUs': 'Contact Us',
    'hero.villagesServed': 'Villages Served',
    'hero.teleconsultation': 'Teleconsultation',
    'hero.reductionTravelTime': 'Reduction in Travel Time',
    
    // Auth
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInDescription': 'Sign in to access your healthcare dashboard',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.signIn': 'Sign In',
    'auth.signingIn': 'Signing In...',
    'auth.noAccount': "Don't have an account?",
    'auth.registerHere': 'Register here',
    'auth.createAccount': 'Create Account',
    'auth.joinDescription': 'Join NabhaCare to access rural healthcare services',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone Number',
    'auth.role': 'Role',
    'auth.patient': 'Patient',
    'auth.doctor': 'Doctor',
    'auth.healthworker': 'Health Worker',
    'auth.village': 'Village/Location',
    'auth.specialization': 'Specialization',
    'auth.licenseNumber': 'License Number',
    'auth.workLocation': 'Work Location',
    'auth.experience': 'Years of Experience',
    'auth.confirmPassword': 'Confirm Password',
    'auth.createAccountBtn': 'Create Account',
    'auth.creatingAccount': 'Creating Account...',
    'auth.haveAccount': 'Already have an account?',
    'auth.signInHere': 'Sign in here',
    
    // Dashboard Common
    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Overview',
    'dashboard.appointments': 'Appointments',
    'dashboard.patients': 'Patients',
    'dashboard.records': 'Health Records',
    'dashboard.medicines': 'Medicines',
    'dashboard.activities': 'Activities',
    'dashboard.consultations': 'Consultations',
    'dashboard.communities': 'Communities',
    'dashboard.alerts': 'Health Alerts',
    
    // Patient Dashboard
    'patient.manageHealth': 'Manage your health and appointments',
    'patient.patientId': 'Patient ID',
    'patient.upcoming': 'Upcoming',
    'patient.healthScore': 'Health Score',
    'patient.good': 'Good',
    'patient.recentActivity': 'Recent Activity',
    'patient.videoCompleted': 'Video consultation completed',
    'patient.recordsUpdated': 'Health records updated',
    'patient.healthSummary': 'Health Summary',
    'patient.bloodPressure': 'Blood Pressure',
    'patient.bloodSugar': 'Blood Sugar',
    'patient.weight': 'Weight',
    'patient.normal': 'Normal',
    'patient.monitor': 'Monitor',
    'patient.stable': 'Stable',
    'patient.bookAppointment': 'Book New Appointment',
    'patient.medicineReminders': 'Medicine Reminders',
    'patient.markTaken': 'Mark Taken',
    'patient.details': 'Details',
    
    // Doctor Dashboard
    'doctor.todayAppointments': "Today's Appointments",
    'doctor.totalPatients': 'Total Patients',
    'doctor.inQueue': 'In Queue',
    'doctor.rating': 'Rating',
    'doctor.todaySchedule': "Today's Schedule",
    'doctor.patientQueue': 'Patient Queue',
    'doctor.startCall': 'Start Call',
    'doctor.complete': 'Complete',
    'doctor.viewCalendar': 'View Calendar',
    'doctor.addSlot': 'Add Slot',
    'doctor.reschedule': 'Reschedule',
    'doctor.completed': 'Completed',
    'doctor.viewPrescription': 'View Prescription',
    'doctor.patientManagement': 'Patient Management',
    'doctor.searchPatients': 'Search patients...',
    'doctor.addPatient': 'Add Patient',
    'doctor.recentConsultations': 'Recent Consultations',
    
    // Health Worker Dashboard
    'healthworker.communityWorker': 'Community Health Worker',
    'healthworker.workerId': 'Worker ID',
    'healthworker.villagesCovered': 'Villages Covered',
    'healthworker.populationServed': 'Population Served',
    'healthworker.activeAlerts': 'Active Alerts',
    'healthworker.avgHealthScore': 'Avg Health Score',
    'healthworker.todayTasks': "Today's Tasks",
    'healthworker.recentActivities': 'Recent Activities',
    'healthworker.markDone': 'Mark Done',
    'healthworker.communityHealth': 'Community Health Overview',
    'healthworker.population': 'Population',
    'healthworker.healthScore': 'Health Score',
    'healthworker.alerts': 'alerts',
    'healthworker.viewDetails': 'View Details',
    'healthworker.createAlert': 'Create Alert',
    'healthworker.logActivity': 'Log Activity',
    
    // Prescription
    'prescription.create': 'Create Prescription',
    'prescription.details': 'Prescription Details',
    'prescription.symptoms': 'Symptoms',
    'prescription.diagnosis': 'Diagnosis',
    'prescription.medicines': 'Prescribed Medicines',
    'prescription.patientInfo': 'Patient Information',
    'prescription.doctorInfo': 'Doctor Information',
    'prescription.additionalNotes': 'Additional Notes',
    'prescription.followUpDate': 'Follow-up Date',
    'prescription.print': 'Print Prescription',
    'prescription.active': 'Active',
    'prescription.medicineName': 'Medicine Name',
    'prescription.dosage': 'Dosage',
    'prescription.frequency': 'Frequency',
    'prescription.duration': 'Duration',
    'prescription.quantity': 'Quantity',
    'prescription.instructions': 'Instructions',
    'prescription.addMedicine': 'Add Medicine',
    'prescription.cancel': 'Cancel',
    'prescription.creating': 'Creating...',
    
    // Solution Section
    'solution.title': 'Our Comprehensive',
    'solution.titleHighlight': 'Healthcare Solution',
    'solution.description': 'A technology platform designed for rural healthcare challenges, providing accessible and quality care.',
    'solution.feature1.title': 'Low-Bandwidth Optimization',
    'solution.feature1.description': 'Designed to work efficiently with limited internet connectivity.',
    'solution.feature1.detail1': 'Offline functionality',
    'solution.feature1.detail2': 'Data compression',
    'solution.feature1.detail3': 'SMS integration',
    'solution.feature2.title': 'Multilingual Telemedicine',
    'solution.feature2.description': 'Video consultations with doctors in Punjabi, Hindi, and English',
    'solution.feature2.detail1': '24/7 availability',
    'solution.feature2.detail2': 'Specialist access',
    'solution.feature2.detail3': 'No travel required',
    'solution.feature3.title': 'Offline Digital Records',
    'solution.feature3.description': 'Digital health records accessible even in low-connectivity areas',
    'solution.feature3.detail1': 'Medical history tracking',
    'solution.feature3.detail2': 'Prescription management',
    'solution.feature3.detail3': 'Offline sync',
    'solution.feature4.title': 'Medicine Availability Tracker',
    'solution.feature4.description': 'Real-time updates on medicine stock at local pharmacies',
    'solution.feature4.detail1': 'Live inventory',
    'solution.feature4.detail2': 'Price comparison',
    'solution.feature4.detail3': 'Reservation system',
    'solution.feature5.title': 'AI Symptom Checker',
    'solution.feature5.description': 'Intelligent preliminary diagnosis optimized for low-bandwidth',
    'solution.feature5.detail1': 'Quick assessment',
    'solution.feature5.detail2': 'Treatment guidance',
    'solution.feature5.detail3': 'Emergency alerts',
    'solution.feature6.title': 'Scalable Platform',
    'solution.feature6.description': 'Built to expand across rural regions throughout India',
    'solution.feature6.detail1': 'Multi-state support',
    'solution.feature6.detail2': 'Local adaptation',
    'solution.feature6.detail3': 'Cloud infrastructure',
    'solution.cta.title': 'Ready to Transform Rural Healthcare?',
    'solution.cta.description': 'Join us in revolutionizing healthcare access for rural communities. Together, we can bridge the gap between villages and quality medical care.',
    'solution.cta.button': 'Get Started Today',
    'solution.previousFeature': 'Previous feature',
    'solution.nextFeature': 'Next feature',

    // Problem Statement Section
    'problem.title': 'The Healthcare Crisis in Rural Punjab',
    'problem.description': 'Thousands of rural residents face significant barriers to accessing quality healthcare, leading to preventable complications and financial hardship.',
    'problem.staffShortage.title': 'Critical Staff Shortage',
    'problem.staffShortage.description': 'Only 11 doctors for 23 sanctioned posts at Nabha Civil Hospital',
    'problem.staffShortage.stat': '48% Staffing',
    'problem.travelTime.title': 'Long Travel Times',
    'problem.travelTime.description': 'Patients from 173 villages travel long distances, often missing work',
    'problem.travelTime.stat': '2-4 Hours',
    'problem.medicineShortage.title': 'Medicine Shortages',
    'problem.medicineShortage.description': 'Frequent stockouts lead to wasted trips and delayed treatment',
    'problem.medicineShortage.stat': '30% Unavailable',
    'problem.financialBurden.title': 'Financial Burden',
    'problem.financialBurden.description': 'Daily-wage earners lose income due to healthcare-related travel',
    'problem.financialBurden.stat': '₹500-1000 Lost/Visit',
    'problem.impact.title': 'Impact on Rural Communities',
    'problem.impact.item1': 'Daily-wage workers and farmers lose income due to healthcare travel',
    'problem.impact.item2': 'Preventable complications worsen due to delayed medical attention',
    'problem.impact.item3': 'Poor road conditions and sanitation further hinder healthcare access',
    'problem.impact.item4': 'Community well-being declines due to inadequate medical care',
    'problem.statistics.title': 'Key Statistics',
    'problem.statistics.internetAccess': 'Internet Access (Rural Punjab)',
    'problem.statistics.villagesServed': 'Villages Served',
    'problem.statistics.doctorShortage': 'Doctor Shortage',

    // Impact Section
    'impact.title': 'Expected Impact',
    'impact.titleAnd': '&',
    'impact.titleAchievements': 'Achievements',
    'impact.description': 'Measuring our success through improved healthcare outcomes, patient satisfaction, and positive community impact across rural Punjab.',
    'impact.achievement1.title': 'Patients Served',
    'impact.achievement1.description': 'Rural patients connected to healthcare',
    'impact.achievement2.title': 'Satisfaction Rate',
    'impact.achievement2.description': 'Patient satisfaction with telemedicine',
    'impact.achievement3.title': 'Time Reduction',
    'impact.achievement3.description': 'Average reduction in healthcare access time',
    'impact.achievement4.title': 'Cost Savings',
    'impact.achievement4.description': 'Average healthcare cost reduction',
    'impact.vision.title': 'Vision for 2025',
    'impact.vision.description': 'Expanding our impact to serve 500+ villages across Punjab and neighboring states, making quality healthcare accessible to every rural community.',
    'impact.vision.stat1.label': 'Villages Connected',
    'impact.vision.stat1.description': 'Expanding across Punjab and neighboring states',
    'impact.vision.stat2.label': 'Patients Served',
    'impact.vision.stat2.description': 'Making quality healthcare accessible',
    'impact.vision.stat3.label': 'Cost Reduction',
    'impact.vision.stat3.description': 'Significant healthcare savings for families',

    // Service Area Map Section
    'servicearea.title': 'Service Coverage Area',
    'servicearea.description': 'Comprehensive healthcare coverage across the Nabha region, connecting rural communities with quality medical care through our innovative telemedicine platform.',
    'servicearea.mapTitle': 'Nabha Region Coverage Map',
    'servicearea.mapAlt': 'Nabha Region Map',
    'servicearea.legend.hub': 'Medical Hub (Nabha)',
    'servicearea.legend.villages': 'Connected Villages',
    'servicearea.stats.title': 'Coverage Statistics',
    'servicearea.stats.coverage': 'Area Coverage',
    'servicearea.stats.connectivity': 'Network Connectivity',
    'servicearea.stats.responseTime': 'Response Time',
    'servicearea.feature1.title': '173 Villages',
    'servicearea.feature1.subtitle': 'Connected Communities',
    'servicearea.feature2.title': 'Real-time',
    'servicearea.feature2.subtitle': 'Health Monitoring',
    'servicearea.cta.title': 'Expand Our Reach',
    'servicearea.cta.description': 'Help us connect more villages and improve rural healthcare accessibility.',
    'servicearea.cta.button': 'Join Our Mission',

    // Footer Section
    'footer.subtitle': 'Nabha Rural Care',
    'footer.description': 'Transforming rural healthcare through technology, connecting 173 villages to quality medical care and improving lives across Punjab.',
    'footer.quickLinks': 'Quick Links',
    'footer.linkProblem': 'The Problem',
    'footer.linkSolution': 'Our Solution',
    'footer.linkImpact': 'Expected Impact',
    'footer.contactInfo': 'Contact Info',
    'footer.address': 'Nabha, Patiala District, Punjab, India',
    'footer.phone': '+91-XXXX-XXXXXX',
    'footer.email': 'info@nabhacare.in',
    'footer.copyright': '© 2025 NabhaCare. All rights reserved. Serving rural Punjab with compassion and technology.',
    'footer.madeWith': 'Made with ❤️ for rural healthcare',

    // Common
    'common.signOut': 'Sign Out',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.status': 'Status',
    'common.scheduled': 'Scheduled',
    'common.ongoing': 'Ongoing',
    'common.cancelled': 'Cancelled',
  },
  hi: {
    // Header
    'header.title': 'नाभाकेयर',
    'header.subtitle': 'नाभा ग्रामीण देखभाल',
    'header.home': 'होम',
    'header.problem': 'समस्या',
    'header.solution': 'समाधान',
    'header.servicearea': 'सेवा क्षेत्र',
    'header.impact': 'प्रभाव',
    'header.signin': 'साइन इन',
    'header.language': 'भाषा',
    
    // Hero Section
    'hero.location': 'नाभा, पंजाब',
    'hero.title': 'स्वास्थ्य सेवा को जोड़ना',
    'hero.subtitle': 'ग्रामीण पंजाब तक',
    'hero.description': 'टेलीमेडिसिन, डिजिटल स्वास्थ्य रिकॉर्ड और एआई-संचालित चिकित्सा सहायता के माध्यम से 173 गांवों को गुणवत्तापूर्ण स्वास्थ्य सेवा से जोड़ना।',
    'hero.learnMore': 'और जानें',
    'hero.contactUs': 'संपर्क करें',
    'hero.villagesServed': 'सेवा प्राप्त गांव',
    'hero.teleconsultation': 'टेली परामर्श',
    'hero.reductionTravelTime': 'यात्रा समय में कमी',
    
    // Auth
    'auth.welcomeBack': 'वापस स्वागत है',
    'auth.signInDescription': 'अपने स्वास्थ्य डैशबोर्ड तक पहुंचने के लिए साइन इन करें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.signIn': 'साइन इन',
    'auth.signingIn': 'साइन इन हो रहा है...',
    'auth.noAccount': 'खाता नहीं है?',
    'auth.registerHere': 'यहाँ पंजीकरण करें',
    'auth.createAccount': 'खाता बनाएं',
    'auth.joinDescription': 'ग्रामीण स्वास्थ्य सेवाओं तक पहुंचने के लिए नाभाकेयर में शामिल हों',
    'auth.firstName': 'पहला नाम',
    'auth.lastName': 'अंतिम नाम',
    'auth.phone': 'फोन नंबर',
    'auth.role': 'भूमिका',
    'auth.patient': 'मरीज़',
    'auth.doctor': 'डॉक्टर',
    'auth.healthworker': 'स्वास्थ्य कार्यकर्ता',
    'auth.village': 'गांव/स्थान',
    'auth.specialization': 'विशेषज्ञता',
    'auth.licenseNumber': 'लाइसेंस नंबर',
    'auth.workLocation': 'कार्य स्थान',
    'auth.experience': 'अनुभव के वर्ष',
    'auth.confirmPassword': 'पासवर्ड की पुष्टि करें',
    'auth.createAccountBtn': 'खाता बनाएं',
    'auth.creatingAccount': 'खाता बनाया जा रहा है...',
    'auth.haveAccount': 'पहले से खाता है?',
    'auth.signInHere': 'यहाँ साइन इन करें',
    
    // Dashboard Common
    'dashboard.welcome': 'वापस स्वागत है',
    'dashboard.overview': 'अवलोकन',
    'dashboard.appointments': 'अपॉइंटमेंट',
    'dashboard.patients': 'मरीज़',
    'dashboard.records': 'स्वास्थ्य रिकॉर्ड',
    'dashboard.medicines': 'दवाइयां',
    'dashboard.activities': 'गतिविधियां',
    'dashboard.consultations': 'परामर्श',
    'dashboard.communities': 'समुदाय',
    'dashboard.alerts': 'स्वास्थ्य अलर्ट',
    
    // Patient Dashboard
    'patient.manageHealth': 'अपने स्वास्थ्य और अपॉइंटमेंट का प्रबंधन करें',
    'patient.patientId': 'मरीज़ आईडी',
    'patient.upcoming': 'आगामी',
    'patient.healthScore': 'स्वास्थ्य स्कोर',
    'patient.good': 'अच्छा',
    'patient.recentActivity': 'हाल की गतिविधि',
    'patient.videoCompleted': 'वीडियो परामर्श पूरा हुआ',
    'patient.recordsUpdated': 'स्वास्थ्य रिकॉर्ड अपडेट किए गए',
    'patient.healthSummary': 'स्वास्थ्य सारांश',
    'patient.bloodPressure': 'रक्तचाप',
    'patient.bloodSugar': 'रक्त शर्करा',
    'patient.weight': 'वजन',
    'patient.normal': 'सामान्य',
    'patient.monitor': 'निगरानी',
    'patient.stable': 'स्थिर',
    'patient.bookAppointment': 'नया अपॉइंटमेंट बुक करें',
    'patient.medicineReminders': 'दवा रिमाइंडर',
    'patient.markTaken': 'लिया गया चिह्नित करें',
    'patient.details': 'विवरण',
    
    // Doctor Dashboard
    'doctor.todayAppointments': 'आज के अपॉइंटमेंट',
    'doctor.totalPatients': 'कुल मरीज़',
    'doctor.inQueue': 'कतार में',
    'doctor.rating': 'रेटिंग',
    'doctor.todaySchedule': 'आज का कार्यक्रम',
    'doctor.patientQueue': 'मरीज़ कतार',
    'doctor.startCall': 'कॉल शुरू करें',
    'doctor.complete': 'पूरा करें',
    'doctor.viewCalendar': 'कैलेंडर देखें',
    'doctor.addSlot': 'स्लॉट जोड़ें',
    'doctor.reschedule': 'पुनर्निर्धारण',
    'doctor.completed': 'पूर्ण',
    'doctor.viewPrescription': 'प्रिस्क्रिप्शन देखें',
    'doctor.patientManagement': 'मरीज़ प्रबंधन',
    'doctor.searchPatients': 'मरीज़ खोजें...',
    'doctor.addPatient': 'मरीज़ जोड़ें',
    'doctor.recentConsultations': 'हाल के परामर्श',
    
    // Health Worker Dashboard
    'healthworker.communityWorker': 'सामुदायिक स्वास्थ्य कार्यकर्ता',
    'healthworker.workerId': 'कार्यकर्ता आईडी',
    'healthworker.villagesCovered': 'कवर किए गए गांव',
    'healthworker.populationServed': 'सेवा प्राप्त जनसंख्या',
    'healthworker.activeAlerts': 'सक्रिय अलर्ट',
    'healthworker.avgHealthScore': 'औसत स्वास्थ्य स्कोर',
    'healthworker.todayTasks': 'आज के कार्य',
    'healthworker.recentActivities': 'हाल की गतिविधियां',
    'healthworker.markDone': 'पूर्ण चिह्नित करें',
    'healthworker.communityHealth': 'सामुदायिक स्वास्थ्य अवलोकन',
    'healthworker.population': 'जनसंख्या',
    'healthworker.healthScore': 'स्वास्थ्य स्कोर',
    'healthworker.alerts': 'अलर्ट',
    'healthworker.viewDetails': 'विवरण देखें',
    'healthworker.createAlert': 'अलर्ट बनाएं',
    'healthworker.logActivity': 'गतिविधि लॉग करें',
    
    // Prescription
    'prescription.create': 'प्रिस्क्रिप्शन बनाएं',
    'prescription.details': 'प्रिस्क्रिप्शन विवरण',
    'prescription.symptoms': 'लक्षण',
    'prescription.diagnosis': 'निदान',
    'prescription.medicines': 'निर्धारित दवाइयां',
    'prescription.patientInfo': 'मरीज़ की जानकारी',
    'prescription.doctorInfo': 'डॉक्टर की जानकारी',
    'prescription.additionalNotes': 'अतिरिक्त नोट्स',
    'prescription.followUpDate': 'फॉलो-अप तारीख',
    'prescription.print': 'प्रिस्क्रिप्शन प्रिंट करें',
    'prescription.active': 'सक्रिय',
    'prescription.medicineName': 'दवा का नाम',
    'prescription.dosage': 'खुराक',
    'prescription.frequency': 'आवृत्ति',
    'prescription.duration': 'अवधि',
    'prescription.quantity': 'मात्रा',
    'prescription.instructions': 'निर्देश',
    'prescription.addMedicine': 'दवा जोड़ें',
    'prescription.cancel': 'रद्द करें',
    'prescription.creating': 'बनाया जा रहा है...',
    
    // Solution Section
    'solution.title': 'हमारा व्यापक',
    'solution.titleHighlight': 'स्वास्थ्य समाधान',
    'solution.description': 'ग्रामीण स्वास्थ्य चुनौतियों के लिए डिज़ाइन किया गया एक तकनीकी मंच, जो सुलभ और गुणवत्तापूर्ण देखभाल प्रदान करता है।',
    'solution.feature1.title': 'कम-बैंडविड्थ अनुकूलन',
    'solution.feature1.description': 'सीमित इंटरनेट कनेक्टिविटी के साथ कुशलता से काम करने के लिए डिज़ाइन किया गया।',
    'solution.feature1.detail1': 'ऑफ़लाइन कार्यक्षमता',
    'solution.feature1.detail2': 'डेटा संपीड़न',
    'solution.feature1.detail3': 'एसएमएस एकीकरण',
    'solution.feature2.title': 'बहुभाषी टेलीमेडिसिन',
    'solution.feature2.description': 'पंजाबी, हिंदी और अंग्रेजी में डॉक्टरों के साथ वीडियो परामर्श',
    'solution.feature2.detail1': '24/7 उपलब्धता',
    'solution.feature2.detail2': 'विशेषज्ञ पहुंच',
    'solution.feature2.detail3': 'यात्रा की आवश्यकता नहीं',
    'solution.feature3.title': 'ऑफ़लाइन डिजिटल रिकॉर्ड',
    'solution.feature3.description': 'कम-कनेक्टिविटी क्षेत्रों में भी सुलभ डिजिटल स्वास्थ्य रिकॉर्ड',
    'solution.feature3.detail1': 'चिकित्सा इतिहास ट्रैकिंग',
    'solution.feature3.detail2': 'प्रिस्क्रिप्शन प्रबंधन',
    'solution.feature3.detail3': 'ऑफ़लाइन सिंक',
    'solution.feature4.title': 'दवा उपलब्धता ट्रैकर',
    'solution.feature4.description': 'स्थानीय फार्मेसियों में दवा स्टॉक पर रियल-टाइम अपडेट',
    'solution.feature4.detail1': 'लाइव इन्वेंटरी',
    'solution.feature4.detail2': 'मूल्य तुलना',
    'solution.feature4.detail3': 'आरक्षण प्रणाली',
    'solution.feature5.title': 'एआई लक्षण जांचकर्ता',
    'solution.feature5.description': 'कम-बैंडविड्थ के लिए अनुकूलित बुद्धिमान प्रारंभिक निदान',
    'solution.feature5.detail1': 'त्वरित मूल्यांकन',
    'solution.feature5.detail2': 'उपचार मार्गदर्शन',
    'solution.feature5.detail3': 'आपातकालीन अलर्ट',
    'solution.feature6.title': 'स्केलेबल प्लेटफॉर्म',
    'solution.feature6.description': 'पूरे भारत में ग्रामीण क्षेत्रों में विस्तार के लिए निर्मित',
    'solution.feature6.detail1': 'बहु-राज्य समर्थन',
    'solution.feature6.detail2': 'स्थानीय अनुकूलन',
    'solution.feature6.detail3': 'क्लाउड इन्फ्रास्ट्रक्चर',
    'solution.cta.title': 'ग्रामीण स्वास्थ्य सेवा को बदलने के लिए तैयार?',
    'solution.cta.description': 'ग्रामीण समुदायों के लिए स्वास्थ्य सेवा पहुंच में क्रांति लाने में हमारे साथ शामिल हों। मिलकर, हम गांवों और गुणवत्तापूर्ण चिकित्सा देखभाल के बीच की दूरी को पाट सकते हैं।',
    'solution.cta.button': 'आज ही शुरुआत करें',
    'solution.previousFeature': 'पिछली विशेषता',
    'solution.nextFeature': 'अगली विशेषता',

    // Problem Statement Section
    'problem.title': 'ग्रामीण पंजाब में स्वास्थ्य संकट',
    'problem.description': 'हजारों ग्रामीण निवासी गुणवत्तापूर्ण स्वास्थ्य सेवा तक पहुंचने में महत्वपूर्ण बाधाओं का सामना करते हैं, जिससे रोकथाम योग्य जटिलताएं और वित्तीय कठिनाई होती है।',
    'problem.staffShortage.title': 'गंभीर स्टाफ की कमी',
    'problem.staffShortage.description': 'नाभा सिविल अस्पताल में 23 स्वीकृत पदों के लिए केवल 11 डॉक्टर',
    'problem.staffShortage.stat': '48% स्टाफिंग',
    'problem.travelTime.title': 'लंबे यात्रा समय',
    'problem.travelTime.description': '173 गांवों के मरीज़ लंबी दूरी की यात्रा करते हैं, अक्सर काम चूकते हैं',
    'problem.travelTime.stat': '2-4 घंटे',
    'problem.medicineShortage.title': 'दवा की कमी',
    'problem.medicineShortage.description': 'बार-बार स्टॉक खत्म होने से व्यर्थ यात्राएं और देरी से उपचार',
    'problem.medicineShortage.stat': '30% अनुपलब्ध',
    'problem.financialBurden.title': 'वित्तीय बोझ',
    'problem.financialBurden.description': 'दैनिक मजदूर स्वास्थ्य सेवा संबंधी यात्रा के कारण आय खो देते हैं',
    'problem.financialBurden.stat': '₹500-1000 हानि/यात्रा',
    'problem.impact.title': 'ग्रामीण समुदायों पर प्रभाव',
    'problem.impact.item1': 'दैनिक मजदूर और किसान स्वास्थ्य यात्रा के कारण आय खो देते हैं',
    'problem.impact.item2': 'देर से चिकित्सा देखभाल के कारण रोकथाम योग्य जटिलताएं बिगड़ती हैं',
    'problem.impact.item3': 'खराब सड़क स्थितियां और स्वच्छता स्वास्थ्य सेवा पहुंच में और बाधा डालती हैं',
    'problem.impact.item4': 'अपर्याप्त चिकित्सा देखभाल के कारण समुदायिक कल्याण में गिरावट',
    'problem.statistics.title': 'मुख्य आंकड़े',
    'problem.statistics.internetAccess': 'इंटरनेट पहुंच (ग्रामीण पंजाब)',
    'problem.statistics.villagesServed': 'सेवा प्राप्त गांव',
    'problem.statistics.doctorShortage': 'डॉक्टर की कमी',

    // Impact Section
    'impact.title': 'अपेक्षित प्रभाव',
    'impact.titleAnd': 'और',
    'impact.titleAchievements': 'उपलब्धियां',
    'impact.description': 'ग्रामीण पंजाब में बेहतर स्वास्थ्य परिणामों, मरीज़ संतुष्टि, और सकारात्मक सामुदायिक प्रभाव के माध्यम से हमारी सफलता को मापना।',
    'impact.achievement1.title': 'सेवा प्राप्त मरीज़',
    'impact.achievement1.description': 'स्वास्थ्य सेवा से जुड़े ग्रामीण मरीज़',
    'impact.achievement2.title': 'संतुष्टि दर',
    'impact.achievement2.description': 'टेलीमेडिसिन के साथ मरीज़ संतुष्टि',
    'impact.achievement3.title': 'समय में कमी',
    'impact.achievement3.description': 'स्वास्थ्य सेवा पहुंच समय में औसत कमी',
    'impact.achievement4.title': 'लागत बचत',
    'impact.achievement4.description': 'औसत स्वास्थ्य सेवा लागत कमी',
    'impact.vision.title': '2025 के लिए दृष्टिकोण',
    'impact.vision.description': 'पंजाब और पड़ोसी राज्यों में 500+ गांवों की सेवा करने के लिए हमारे प्रभाव का विस्तार, हर ग्रामीण समुदाय के लिए गुणवत्तापूर्ण स्वास्थ्य सेवा सुलभ बनाना।',
    'impact.vision.stat1.label': 'जुड़े गांव',
    'impact.vision.stat1.description': 'पंजाब और पड़ोसी राज्यों में विस्तार',
    'impact.vision.stat2.label': 'सेवा प्राप्त मरीज़',
    'impact.vision.stat2.description': 'गुणवत्तापूर्ण स्वास्थ्य सेवा सुलभ बनाना',
    'impact.vision.stat3.label': 'लागत कमी',
    'impact.vision.stat3.description': 'परिवारों के लिए महत्वपूर्ण स्वास्थ्य बचत',

    // Service Area Map Section
    'servicearea.title': 'सेवा कवरेज क्षेत्र',
    'servicearea.description': 'नाभा क्षेत्र में व्यापक स्वास्थ्य सेवा कवरेज, हमारे नवाचार टेलीमेडिसिन प्लेटफॉर्म के माध्यम से ग्रामीण समुदायों को गुणवत्तापूर्ण चिकित्सा देखभाल से जोड़ना।',
    'servicearea.mapTitle': 'नाभा क्षेत्र कवरेज मानचित्र',
    'servicearea.mapAlt': 'नाभा क्षेत्र मानचित्र',
    'servicearea.legend.hub': 'चिकित्सा केंद्र (नाभा)',
    'servicearea.legend.villages': 'जुड़े गांव',
    'servicearea.stats.title': 'कवरेज आंकड़े',
    'servicearea.stats.coverage': 'क्षेत्र कवरेज',
    'servicearea.stats.connectivity': 'नेटवर्क कनेक्टिविटी',
    'servicearea.stats.responseTime': 'प्रतिक्रिया समय',
    'servicearea.feature1.title': '173 गांव',
    'servicearea.feature1.subtitle': 'जुड़े समुदाय',
    'servicearea.feature2.title': 'रियल-टाइम',
    'servicearea.feature2.subtitle': 'स्वास्थ्य निगरानी',
    'servicearea.cta.title': 'हमारी पहुंच बढ़ाएं',
    'servicearea.cta.description': 'अधिक गांवों को जोड़ने और ग्रामीण स्वास्थ्य सेवा पहुंच में सुधार करने में हमारी मदद करें।',
    'servicearea.cta.button': 'हमारे मिशन में शामिल हों',

    // Footer Section
    'footer.subtitle': 'नाभा ग्रामीण देखभाल',
    'footer.description': 'तकनीक के माध्यम से ग्रामीण स्वास्थ्य सेवा का रूपांतरण, 173 गांवों को गुणवत्तापूर्ण चिकित्सा देखभाल से जोड़ना और पंजाब में जीवन सुधारना।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.linkProblem': 'समस्या',
    'footer.linkSolution': 'हमारा समाधान',
    'footer.linkImpact': 'अपेक्षित प्रभाव',
    'footer.contactInfo': 'संपर्क जानकारी',
    'footer.address': 'नाभा, पटियाला जिला, पंजाब, भारत',
    'footer.phone': '+91-XXXX-XXXXXX',
    'footer.email': 'info@nabhacare.in',
    'footer.copyright': '© 2025 नाभाकेयर। सभी अधिकार सुरक्षित। करुणा और तकनीक के साथ ग्रामीण पंजाब की सेवा।',
    'footer.madeWith': 'ग्रामीण स्वास्थ्य सेवा के लिए ❤️ से बनाया गया',

    // Common
    'common.signOut': 'साइन आउट',
    'common.close': 'बंद करें',
    'common.save': 'सेव करें',
    'common.edit': 'संपादित करें',
    'common.delete': 'हटाएं',
    'common.view': 'देखें',
    'common.date': 'तारीख',
    'common.time': 'समय',
    'common.status': 'स्थिति',
    'common.scheduled': 'निर्धारित',
    'common.ongoing': 'चल रहा',
    'common.cancelled': 'रद्द',
  },
  pa: {
    // Header
    'header.title': 'ਨਾਭਾਕੇਅਰ',
    'header.subtitle': 'ਨਾਭਾ ਪੇਂਡੂ ਦੇਖਭਾਲ',
    'header.home': 'ਘਰ',
    'header.problem': 'ਸਮੱਸਿਆ',
    'header.solution': 'ਹੱਲ',
    'header.servicearea': 'ਸੇਵਾ ਖੇਤਰ',
    'header.impact': 'ਪ੍ਰਭਾਵ',
    'header.signin': 'ਸਾਈਨ ਇਨ',
    'header.language': 'ਭਾਸ਼ਾ',
    
    // Hero Section
    'hero.location': 'ਨਾਭਾ, ਪੰਜਾਬ',
    'hero.title': 'ਸਿਹਤ ਸੇਵਾ ਨੂੰ ਜੋੜਨਾ',
    'hero.subtitle': 'ਪੇਂਡੂ ਪੰਜਾਬ ਤੱਕ',
    'hero.description': 'ਟੈਲੀਮੈਡੀਸਿਨ, ਡਿਜੀਟਲ ਸਿਹਤ ਰਿਕਾਰਡ ਅਤੇ ਏਆਈ-ਸੰਚਾਲਿਤ ਮੈਡੀਕਲ ਸਹਾਇਤਾ ਰਾਹੀਂ 173 ਪਿੰਡਾਂ ਨੂੰ ਗੁਣਵੱਤਾ ਸਿਹਤ ਸੇਵਾ ਨਾਲ ਜੋੜਨਾ।',
    'hero.learnMore': 'ਹੋਰ ਜਾਣੋ',
    'hero.contactUs': 'ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    'hero.villagesServed': 'ਸੇਵਾ ਪ੍ਰਾਪਤ ਪਿੰਡ',
    'hero.teleconsultation': 'ਟੈਲੀ ਸਲਾਹ',
    'hero.reductionTravelTime': 'ਯਾਤਰਾ ਸਮੇਂ ਵਿੱਚ ਕਮੀ',
    
    // Auth
    'auth.welcomeBack': 'ਵਾਪਸ ਜੀ ਆਇਆਂ ਨੂੰ',
    'auth.signInDescription': 'ਆਪਣੇ ਸਿਹਤ ਡੈਸ਼ਬੋਰਡ ਤੱਕ ਪਹੁੰਚ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
    'auth.email': 'ਈਮੇਲ ਪਤਾ',
    'auth.password': 'ਪਾਸਵਰਡ',
    'auth.signIn': 'ਸਾਈਨ ਇਨ',
    'auth.signingIn': 'ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
    'auth.noAccount': 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    'auth.registerHere': 'ਇੱਥੇ ਰਜਿਸਟਰ ਕਰੋ',
    'auth.createAccount': 'ਖਾਤਾ ਬਣਾਓ',
    'auth.joinDescription': 'ਪੇਂਡੂ ਸਿਹਤ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚ ਲਈ ਨਾਭਾਕੇਅਰ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    'auth.firstName': 'ਪਹਿਲਾ ਨਾਮ',
    'auth.lastName': 'ਅੰਤਿਮ ਨਾਮ',
    'auth.phone': 'ਫੋਨ ਨੰਬਰ',
    'auth.role': 'ਭੂਮਿਕਾ',
    'auth.patient': 'ਮਰੀਜ਼',
    'auth.doctor': 'ਡਾਕਟਰ',
    'auth.healthworker': 'ਸਿਹਤ ਕਰਮਚਾਰੀ',
    'auth.village': 'ਪਿੰਡ/ਸਥਾਨ',
    'auth.specialization': 'ਵਿਸ਼ੇਸ਼ਤਾ',
    'auth.licenseNumber': 'ਲਾਇਸੈਂਸ ਨੰਬਰ',
    'auth.workLocation': 'ਕੰਮ ਦਾ ਸਥਾਨ',
    'auth.experience': 'ਤਜਰਬੇ ਦੇ ਸਾਲ',
    'auth.confirmPassword': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'auth.createAccountBtn': 'ਖਾਤਾ ਬਣਾਓ',
    'auth.creatingAccount': 'ਖਾਤਾ ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
    'auth.haveAccount': 'ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ?',
    'auth.signInHere': 'ਇੱਥੇ ਸਾਈਨ ਇਨ ਕਰੋ',
    
    // Dashboard Common
    'dashboard.welcome': 'ਵਾਪਸ ਜੀ ਆਇਆਂ ਨੂੰ',
    'dashboard.overview': 'ਸੰਖੇਪ',
    'dashboard.appointments': 'ਮੁਲਾਕਾਤਾਂ',
    'dashboard.patients': 'ਮਰੀਜ਼',
    'dashboard.records': 'ਸਿਹਤ ਰਿਕਾਰਡ',
    'dashboard.medicines': 'ਦਵਾਈਆਂ',
    'dashboard.activities': 'ਗਤੀਵਿਧੀਆਂ',
    'dashboard.consultations': 'ਸਲਾਹ',
    'dashboard.communities': 'ਕਮਿਊਨਿਟੀਆਂ',
    'dashboard.alerts': 'ਸਿਹਤ ਅਲਰਟ',
    
    // Patient Dashboard
    'patient.manageHealth': 'ਆਪਣੀ ਸਿਹਤ ਅਤੇ ਮੁਲਾਕਾਤਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
    'patient.patientId': 'ਮਰੀਜ਼ ਆਈਡੀ',
    'patient.upcoming': 'ਆਉਣ ਵਾਲੀਆਂ',
    'patient.healthScore': 'ਸਿਹਤ ਸਕੋਰ',
    'patient.good': 'ਚੰਗਾ',
    'patient.recentActivity': 'ਹਾਲ ਦੀ ਗਤੀਵਿਧੀ',
    'patient.videoCompleted': 'ਵੀਡੀਓ ਸਲਾਹ ਪੂਰੀ ਹੋਈ',
    'patient.recordsUpdated': 'ਸਿਹਤ ਰਿਕਾਰਡ ਅਪਡੇਟ ਕੀਤੇ ਗਏ',
    'patient.healthSummary': 'ਸਿਹਤ ਸਾਰ',
    'patient.bloodPressure': 'ਬਲੱਡ ਪ੍ਰੈਸ਼ਰ',
    'patient.bloodSugar': 'ਬਲੱਡ ਸ਼ੂਗਰ',
    'patient.weight': 'ਭਾਰ',
    'patient.normal': 'ਸਾਧਾਰਨ',
    'patient.monitor': 'ਨਿਗਰਾਨੀ',
    'patient.stable': 'ਸਥਿਰ',
    'patient.bookAppointment': 'ਨਵੀਂ ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ',
    'patient.medicineReminders': 'ਦਵਾਈ ਰਿਮਾਈਂਡਰ',
    'patient.markTaken': 'ਲਿਆ ਗਿਆ ਮਾਰਕ ਕਰੋ',
    'patient.details': 'ਵੇਰਵੇ',
    
    // Doctor Dashboard
    'doctor.todayAppointments': 'ਅੱਜ ਦੀਆਂ ਮੁਲਾਕਾਤਾਂ',
    'doctor.totalPatients': 'ਕੁੱਲ ਮਰੀਜ਼',
    'doctor.inQueue': 'ਕਤਾਰ ਵਿੱਚ',
    'doctor.rating': 'ਰੇਟਿੰਗ',
    'doctor.todaySchedule': 'ਅੱਜ ਦਾ ਕਾਰਯਕ੍ਰਮ',
    'doctor.patientQueue': 'ਮਰੀਜ਼ ਕਤਾਰ',
    'doctor.startCall': 'ਕਾਲ ਸ਼ੁਰੂ ਕਰੋ',
    'doctor.complete': 'ਪੂਰਾ ਕਰੋ',
    'doctor.viewCalendar': 'ਕੈਲੰਡਰ ਦੇਖੋ',
    'doctor.addSlot': 'ਸਲਾਟ ਜੋੜੋ',
    'doctor.reschedule': 'ਮੁੜ ਨਿਰਧਾਰਨ',
    'doctor.completed': 'ਪੂਰਾ',
    'doctor.viewPrescription': 'ਨੁਸਖਾ ਦੇਖੋ',
    'doctor.patientManagement': 'ਮਰੀਜ਼ ਪ੍ਰਬੰਧਨ',
    'doctor.searchPatients': 'ਮਰੀਜ਼ ਖੋਜੋ...',
    'doctor.addPatient': 'ਮਰੀਜ਼ ਜੋੜੋ',
    'doctor.recentConsultations': 'ਹਾਲ ਦੀਆਂ ਸਲਾਹਾਂ',
    
    // Health Worker Dashboard
    'healthworker.communityWorker': 'ਕਮਿਊਨਿਟੀ ਸਿਹਤ ਕਰਮਚਾਰੀ',
    'healthworker.workerId': 'ਕਰਮਚਾਰੀ ਆਈਡੀ',
    'healthworker.villagesCovered': 'ਕਵਰ ਕੀਤੇ ਪਿੰਡ',
    'healthworker.populationServed': 'ਸੇਵਾ ਪ੍ਰਾਪਤ ਆਬਾਦੀ',
    'healthworker.activeAlerts': 'ਸਰਗਰਮ ਅਲਰਟ',
    'healthworker.avgHealthScore': 'ਔਸਤ ਸਿਹਤ ਸਕੋਰ',
    'healthworker.todayTasks': 'ਅੱਜ ਦੇ ਕੰਮ',
    'healthworker.recentActivities': 'ਹਾਲ ਦੀਆਂ ਗਤੀਵਿਧੀਆਂ',
    'healthworker.markDone': 'ਪੂਰਾ ਮਾਰਕ ਕਰੋ',
    'healthworker.communityHealth': 'ਕਮਿਊਨਿਟੀ ਸਿਹਤ ਸੰਖੇਪ',
    'healthworker.population': 'ਆਬਾਦੀ',
    'healthworker.healthScore': 'ਸਿਹਤ ਸਕੋਰ',
    'healthworker.alerts': 'ਅਲਰਟ',
    'healthworker.viewDetails': 'ਵੇਰਵੇ ਦੇਖੋ',
    'healthworker.createAlert': 'ਅਲਰਟ ਬਣਾਓ',
    'healthworker.logActivity': 'ਗਤੀਵਿਧੀ ਲਾਗ ਕਰੋ',
    
    // Prescription
    'prescription.create': 'ਨੁਸਖਾ ਬਣਾਓ',
    'prescription.details': 'ਨੁਸਖਾ ਵੇਰਵੇ',
    'prescription.symptoms': 'ਲੱਛਣ',
    'prescription.diagnosis': 'ਨਿਦਾਨ',
    'prescription.medicines': 'ਨਿਰਧਾਰਿਤ ਦਵਾਈਆਂ',
    'prescription.patientInfo': 'ਮਰੀਜ਼ ਦੀ ਜਾਣਕਾਰੀ',
    'prescription.doctorInfo': 'ਡਾਕਟਰ ਦੀ ਜਾਣਕਾਰੀ',
    'prescription.additionalNotes': 'ਵਾਧੂ ਨੋਟਸ',
    'prescription.followUpDate': 'ਫਾਲੋ-ਅੱਪ ਤਾਰੀਖ',
    'prescription.print': 'ਨੁਸਖਾ ਪ੍ਰਿੰਟ ਕਰੋ',
    'prescription.active': 'ਸਰਗਰਮ',
    'prescription.medicineName': 'ਦਵਾਈ ਦਾ ਨਾਮ',
    'prescription.dosage': 'ਖੁਰਾਕ',
    'prescription.frequency': 'ਬਾਰੰਬਾਰਤਾ',
    'prescription.duration': 'ਮਿਆਦ',
    'prescription.quantity': 'ਮਾਤਰਾ',
    'prescription.instructions': 'ਨਿਰਦੇਸ਼',
    'prescription.addMedicine': 'ਦਵਾਈ ਜੋੜੋ',
    'prescription.cancel': 'ਰੱਦ ਕਰੋ',
    'prescription.creating': 'ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...',
    
    // Solution Section
    'solution.title': 'ਸਾਡਾ ਵਿਆਪਕ',
    'solution.titleHighlight': 'ਸਿਹਤ ਹੱਲ',
    'solution.description': 'ਪੇਂਡੂ ਸਿਹਤ ਚੁਣੌਤੀਆਂ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਤਕਨੀਕੀ ਪਲੇਟਫਾਰਮ, ਪਹੁੰਚਯੋਗ ਅਤੇ ਗੁਣਵੱਤਾ ਦੇਖਭਾਲ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।',
    'solution.feature1.title': 'ਘੱਟ-ਬੈਂਡਵਿਡਥ ਅਨੁਕੂਲਨ',
    'solution.feature1.description': 'ਸੀਮਿਤ ਇੰਟਰਨੈੱਟ ਕਨੈਕਟਿਵਿਟੀ ਨਾਲ ਕੁਸ਼ਲਤਾ ਨਾਲ ਕੰਮ ਕਰਨ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ।',
    'solution.feature1.detail1': 'ਆਫਲਾਈਨ ਕਾਰਜਸ਼ੀਲਤਾ',
    'solution.feature1.detail2': 'ਡਾਟਾ ਸੰਪੀੜਨ',
    'solution.feature1.detail3': 'ਐਸਐਮਐਸ ਏਕੀਕਰਨ',
    'solution.feature2.title': 'ਬਹੁਭਾਸ਼ੀ ਟੈਲੀਮੈਡੀਸਿਨ',
    'solution.feature2.description': 'ਪੰਜਾਬੀ, ਹਿੰਦੀ ਅਤੇ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਡਾਕਟਰਾਂ ਨਾਲ ਵੀਡੀਓ ਸਲਾਹ',
    'solution.feature2.detail1': '24/7 ਉਪਲਬਧਤਾ',
    'solution.feature2.detail2': 'ਵਿਸ਼ੇਸ਼ਗਿਆ ਪਹੁੰਚ',
    'solution.feature2.detail3': 'ਯਾਤਰਾ ਦੀ ਲੋੜ ਨਹੀਂ',
    'solution.feature3.title': 'ਆਫਲਾਈਨ ਡਿਜੀਟਲ ਰਿਕਾਰਡ',
    'solution.feature3.description': 'ਘੱਟ-ਕਨੈਕਟਿਵਿਟੀ ਖੇਤਰਾਂ ਵਿੱਚ ਵੀ ਪਹੁੰਚਯੋਗ ਡਿਜੀਟਲ ਸਿਹਤ ਰਿਕਾਰਡ',
    'solution.feature3.detail1': 'ਮੈਡੀਕਲ ਇਤਿਹਾਸ ਟਰੈਕਿੰਗ',
    'solution.feature3.detail2': 'ਨੁਸਖਾ ਪ੍ਰਬੰਧਨ',
    'solution.feature3.detail3': 'ਆਫਲਾਈਨ ਸਿੰਕ',
    'solution.feature4.title': 'ਦਵਾਈ ਉਪਲਬਧਤਾ ਟਰੈਕਰ',
    'solution.feature4.description': 'ਸਥਾਨਕ ਫਾਰਮੇਸੀਆਂ ਵਿੱਚ ਦਵਾਈ ਸਟਾਕ ਉੱਤੇ ਰੀਅਲ-ਟਾਈਮ ਅਪਡੇਟ',
    'solution.feature4.detail1': 'ਲਾਈਵ ਇਨਵੇਂਟਰੀ',
    'solution.feature4.detail2': 'ਕੀਮਤ ਤੁਲਨਾ',
    'solution.feature4.detail3': 'ਰਿਜ਼ਰਵੇਸ਼ਨ ਸਿਸਟਮ',
    'solution.feature5.title': 'ਏਆਈ ਲੱਛਣ ਜਾਂਚਕਰਤਾ',
    'solution.feature5.description': 'ਘੱਟ-ਬੈਂਡਵਿਡਥ ਲਈ ਅਨੁਕੂਲਿਤ ਬੁੱਧੀਮਾਨ ਸ਼ੁਰੂਆਤੀ ਨਿਦਾਨ',
    'solution.feature5.detail1': 'ਤੇਜ਼ ਮੁਲਾਂਕਣ',
    'solution.feature5.detail2': 'ਇਲਾਜ ਮਾਰਗਦਰਸ਼ਨ',
    'solution.feature5.detail3': 'ਐਮਰਜੈਂਸੀ ਅਲਰਟ',
    'solution.feature6.title': 'ਸਕੇਲੇਬਲ ਪਲੇਟਫਾਰਮ',
    'solution.feature6.description': 'ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਪੇਂਡੂ ਖੇਤਰਾਂ ਵਿੱਚ ਫੈਲਾਉਣ ਲਈ ਬਣਾਇਆ ਗਿਆ',
    'solution.feature6.detail1': 'ਬਹੁ-ਰਾਜ ਸਹਾਇਤਾ',
    'solution.feature6.detail2': 'ਸਥਾਨਕ ਅਨੁਕੂਲਨ',
    'solution.feature6.detail3': 'ਕਲਾਊਡ ਇਨਫਰਾਸਟਰਕਚਰ',
    'solution.cta.title': 'ਪੇਂਡੂ ਸਿਹਤ ਸੇਵਾ ਨੂੰ ਬਦਲਣ ਲਈ ਤਿਆਰ?',
    'solution.cta.description': 'ਪੇਂਡੂ ਕਮਿਊਨਿਟੀਆਂ ਲਈ ਸਿਹਤ ਸੇਵਾ ਪਹੁੰਚ ਵਿੱਚ ਇਨਕਲਾਬ ਲਿਆਉਣ ਵਿੱਚ ਸਾਡੇ ਨਾਲ ਸ਼ਾਮਲ ਹੋਵੋ। ਮਿਲ ਕੇ, ਅਸੀਂ ਪਿੰਡਾਂ ਅਤੇ ਗੁਣਵੱਤਾ ਮੈਡੀਕਲ ਦੇਖਭਾਲ ਵਿਚਕਾਰ ਪਾੜ ਨੂੰ ਪਾਟ ਸਕਦੇ ਹਾਂ।',
    'solution.cta.button': 'ਅੱਜ ਹੀ ਸ਼ੁਰੂਆਤ ਕਰੋ',
    'solution.previousFeature': 'ਪਿਛਲੀ ਵਿਸ਼ੇਸ਼ਤਾ',
    'solution.nextFeature': 'ਅਗਲੀ ਵਿਸ਼ੇਸ਼ਤਾ',

    // Problem Statement Section
    'problem.title': 'ਪੇਂਡੂ ਪੰਜਾਬ ਵਿੱਚ ਸਿਹਤ ਸੰਕਟ',
    'problem.description': 'ਹਜ਼ਾਰਾਂ ਪੇਂਡੂ ਨਿਵਾਸੀ ਗੁਣਵੱਤਾ ਸਿਹਤ ਸੇਵਾ ਤੱਕ ਪਹੁੰਚ ਵਿੱਚ ਮਹੱਤਵਪੂਰਨ ਰੁਕਾਵਟਾਂ ਦਾ ਸਾਮਣਾ ਕਰਦੇ ਹਨ, ਜਿਸ ਕਾਰਨ ਰੋਕਥਾਮਯੋਗ ਜਟਿਲਤਾਵਾਂ ਅਤੇ ਵਿੱਤੀ ਮੁਸ਼ਕਿਲ ਹੁੰਦੀ ਹੈ।',
    'problem.staffShortage.title': 'ਗੰਭੀਰ ਸਟਾਫ ਦੀ ਕਮੀ',
    'problem.staffShortage.description': 'ਨਾਭਾ ਸਿਵਲ ਹਸਪਤਾਲ ਵਿੱਚ 23 ਮਨਜ਼ੂਰ ਅਸਾਮੀਆਂ ਲਈ ਸਿਰਫ 11 ਡਾਕਟਰ',
    'problem.staffShortage.stat': '48% ਸਟਾਫਿੰਗ',
    'problem.travelTime.title': 'ਲੰਬੇ ਯਾਤਰਾ ਸਮੇਂ',
    'problem.travelTime.description': '173 ਪਿੰਡਾਂ ਦੇ ਮਰੀਜ਼ ਲੰਬੀ ਦੂਰੀ ਦੀ ਯਾਤਰਾ ਕਰਦੇ ਹਨ, ਅਕਸਰ ਕੰਮ ਛੁੱਟਦਾ ਹੈ',
    'problem.travelTime.stat': '2-4 ਘੰਟੇ',
    'problem.medicineShortage.title': 'ਦਵਾਈ ਦੀ ਕਮੀ',
    'problem.medicineShortage.description': 'ਵਾਰ-ਵਾਰ ਸਟਾਕ ਖਤਮ ਹੋਣ ਕਾਰਨ ਵਿਅਰਥ ਯਾਤਰਾਵਾਂ ਅਤੇ ਦੇਰ ਨਾਲ ਇਲਾਜ',
    'problem.medicineShortage.stat': '30% ਉਪਲਬਧ ਨਹੀਂ',
    'problem.financialBurden.title': 'ਵਿੱਤੀ ਬੋਝ',
    'problem.financialBurden.description': 'ਰੋਜ਼ਾਨਾ ਮਜ਼ਦੂਰ ਸਿਹਤ ਸੇਵਾ ਸੰਬੰਧੀ ਯਾਤਰਾ ਕਾਰਨ ਆਮਦਨ ਗੁਆ ਦਿੰਦੇ ਹਨ',
    'problem.financialBurden.stat': '₹500-1000 ਨੁਕਸਾਨ/ਯਾਤਰਾ',
    'problem.impact.title': 'ਪੇਂਡੂ ਕਮਿਊਨਿਟੀਆਂ ਉੱਤੇ ਪ੍ਰਭਾਵ',
    'problem.impact.item1': 'ਰੋਜ਼ਾਨਾ ਮਜ਼ਦੂਰ ਅਤੇ ਕਿਸਾਨ ਸਿਹਤ ਯਾਤਰਾ ਕਾਰਨ ਆਮਦਨ ਗੁਆ ਦਿੰਦੇ ਹਨ',
    'problem.impact.item2': 'ਦੇਰ ਨਾਲ ਡਾਕਟਰੀ ਦੇਖਭਾਲ ਕਾਰਨ ਰੋਕਥਾਮਯੋਗ ਜਟਿਲਤਾਵਾਂ ਵਿਗੜਦੀਆਂ ਹਨ',
    'problem.impact.item3': 'ਖਰਾਬ ਸੜਕ ਸਥਿਤੀਆਂ ਅਤੇ ਸਫਾਈ ਸਿਹਤ ਸੇਵਾ ਪਹੁੰਚ ਵਿੱਚ ਹੋਰ ਰੁਕਾਵਟ ਪਾਉਂਦੀ ਹੈ',
    'problem.impact.item4': 'ਨਾਕਾਫੀ ਡਾਕਟਰੀ ਦੇਖਭਾਲ ਕਾਰਨ ਕਮਿਊਨਿਟੀ ਭਲਾਈ ਵਿੱਚ ਗਿਰਾਵਟ',
    'problem.statistics.title': 'ਮੁੱਖ ਅੰਕੜੇ',
    'problem.statistics.internetAccess': 'ਇੰਟਰਨੈੱਟ ਪਹੁੰਚ (ਪੇਂਡੂ ਪੰਜਾਬ)',
    'problem.statistics.villagesServed': 'ਸੇਵਾ ਪ੍ਰਾਪਤ ਪਿੰਡ',
    'problem.statistics.doctorShortage': 'ਡਾਕਟਰ ਦੀ ਕਮੀ',

    // Impact Section
    'impact.title': 'ਉਮੀਦ ਕੀਤਾ ਪ੍ਰਭਾਵ',
    'impact.titleAnd': 'ਅਤੇ',
    'impact.titleAchievements': 'ਪ੍ਰਾਪਤੀਆਂ',
    'impact.description': 'ਪੇਂਡੂ ਪੰਜਾਬ ਵਿੱਚ ਬਿਹਤਰ ਸਿਹਤ ਨਤੀਜਿਆਂ, ਮਰੀਜ਼ ਸੰਤੁਸ਼ਟਤਾ, ਅਤੇ ਸਕਾਰਾਤਮਕ ਕਮਿਊਨਿਟੀ ਪ੍ਰਭਾਵ ਰਾਹੀਂ ਸਾਡੀ ਸਫਲਤਾ ਨੂੰ ਮਾਪਣਾ।',
    'impact.achievement1.title': 'ਸੇਵਾ ਪ੍ਰਾਪਤ ਮਰੀਜ਼',
    'impact.achievement1.description': 'ਸਿਹਤ ਸੇਵਾ ਨਾਲ ਜੁੜੇ ਪੇਂਡੂ ਮਰੀਜ਼',
    'impact.achievement2.title': 'ਸੰਤੁਸ਼ਟਤਾ ਦਰ',
    'impact.achievement2.description': 'ਟੈਲੀਮੈਡੀਸਿਨ ਨਾਲ ਮਰੀਜ਼ ਸੰਤੁਸ਼ਟਤਾ',
    'impact.achievement3.title': 'ਸਮੇਂ ਵਿੱਚ ਕਮੀ',
    'impact.achievement3.description': 'ਸਿਹਤ ਸੇਵਾ ਪਹੁੰਚ ਸਮੇਂ ਵਿੱਚ ਔਸਤ ਕਮੀ',
    'impact.achievement4.title': 'ਲਾਗਤ ਬਚਤ',
    'impact.achievement4.description': 'ਔਸਤ ਸਿਹਤ ਸੇਵਾ ਲਾਗਤ ਕਮੀ',
    'impact.vision.title': '2025 ਲਈ ਦਰਸ਼ਨ',
    'impact.vision.description': 'ਪੰਜਾਬ ਅਤੇ ਨੇੜਲੇ ਰਾਜਾਂ ਵਿੱਚ 500+ ਪਿੰਡਾਂ ਦੀ ਸੇਵਾ ਕਰਨ ਲਈ ਸਾਡੇ ਪ੍ਰਭਾਵ ਦਾ ਵਿਸਤਾਰ, ਹਰ ਪੇਂਡੂ ਕਮਿਊਨਿਟੀ ਲਈ ਗੁਣਵੱਤਾ ਸਿਹਤ ਸੇਵਾ ਪਹੁੰਚਯੋਗ ਬਣਾਉਣਾ।',
    'impact.vision.stat1.label': 'ਜੁੜੇ ਪਿੰਡ',
    'impact.vision.stat1.description': 'ਪੰਜਾਬ ਅਤੇ ਨੇੜਲੇ ਰਾਜਾਂ ਵਿੱਚ ਫੈਲਾਅ',
    'impact.vision.stat2.label': 'ਸੇਵਾ ਪ੍ਰਾਪਤ ਮਰੀਜ਼',
    'impact.vision.stat2.description': 'ਗੁਣਵੱਤਾ ਸਿਹਤ ਸੇਵਾ ਪਹੁੰਚਯੋਗ ਬਣਾਉਣਾ',
    'impact.vision.stat3.label': 'ਲਾਗਤ ਕਮੀ',
    'impact.vision.stat3.description': 'ਪਰਿਵਾਰਾਂ ਲਈ ਮਹੱਤਵਪੂਰਨ ਸਿਹਤ ਬਚਤ',

    // Service Area Map Section
    'servicearea.title': 'ਸੇਵਾ ਕਵਰੇਜ ਖੇਤਰ',
    'servicearea.description': 'ਨਾਭਾ ਖੇਤਰ ਵਿੱਚ ਵਿਆਪਕ ਸਿਹਤ ਸੇਵਾ ਕਵਰੇਜ, ਸਾਡੇ ਨਵੀਨ ਟੈਲੀਮੈਡੀਸਿਨ ਪਲੇਟਫਾਰਮ ਰਾਹੀਂ ਪੇਂਡੂ ਕਮਿਊਨਿਟੀਆਂ ਨੂੰ ਗੁਣਵੱਤਾ ਮੈਡੀਕਲ ਦੇਖਭਾਲ ਨਾਲ ਜੋੜਨਾ।',
    'servicearea.mapTitle': 'ਨਾਭਾ ਖੇਤਰ ਕਵਰੇਜ ਨਕਸ਼ਾ',
    'servicearea.mapAlt': 'ਨਾਭਾ ਖੇਤਰ ਨਕਸ਼ਾ',
    'servicearea.legend.hub': 'ਮੈਡੀਕਲ ਕੇਂਦਰ (ਨਾਭਾ)',
    'servicearea.legend.villages': 'ਜੁੜੇ ਪਿੰਡ',
    'servicearea.stats.title': 'ਕਵਰੇਜ ਅੰਕੜੇ',
    'servicearea.stats.coverage': 'ਖੇਤਰ ਕਵਰੇਜ',
    'servicearea.stats.connectivity': 'ਨੈਟਵਰਕ ਕਨੈਕਟਿਵਿਟੀ',
    'servicearea.stats.responseTime': 'ਜਵਾਬ ਸਮਾਂ',
    'servicearea.feature1.title': '173 ਪਿੰਡ',
    'servicearea.feature1.subtitle': 'ਜੁੜੇ ਕਮਿਊਨਿਟੀਜ਼',
    'servicearea.feature2.title': 'ਰੀਅਲ-ਟਾਈਮ',
    'servicearea.feature2.subtitle': 'ਸਿਹਤ ਨਿਗਰਾਨੀ',
    'servicearea.cta.title': 'ਸਾਡੀ ਪਹੁੰਚ ਵਧਾਓ',
    'servicearea.cta.description': 'ਹੋਰ ਪਿੰਡਾਂ ਨੂੰ ਜੋੜਨ ਅਤੇ ਪੇਂਡੂ ਸਿਹਤ ਸੇਵਾ ਪਹੁੰਚ ਵਿੱਚ ਸੁਧਾਰ ਕਰਨ ਵਿੱਚ ਸਾਡੀ ਮਦਦ ਕਰੋ।',
    'servicearea.cta.button': 'ਸਾਡੇ ਮਿਸ਼ਨ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',

    // Footer Section
    'footer.subtitle': 'ਨਾਭਾ ਪੇਂਡੂ ਦੇਖਭਾਲ',
    'footer.description': 'ਤਕਨੀਕ ਰਾਹੀਂ ਪੇਂਡੂ ਸਿਹਤ ਸੇਵਾ ਦਾ ਰੂਪਾਂਤਰਨ, 173 ਪਿੰਡਾਂ ਨੂੰ ਗੁਣਵੱਤਾ ਮੈਡੀਕਲ ਦੇਖਭਾਲ ਨਾਲ ਜੋੜਨਾ ਅਤੇ ਪੰਜਾਬ ਵਿੱਚ ਜੀਵਨ ਸੁਧਾਰਨਾ।',
    'footer.quickLinks': 'ਤੇਜ਼ ਲਿੰਕ',
    'footer.linkProblem': 'ਸਮੱਸਿਆ',
    'footer.linkSolution': 'ਸਾਡਾ ਹੱਲ',
    'footer.linkImpact': 'ਉਮੀਦ ਕੀਤਾ ਪ੍ਰਭਾਵ',
    'footer.contactInfo': 'ਸੰਪਰਕ ਜਾਣਕਾਰੀ',
    'footer.address': 'ਨਾਭਾ, ਪਟਿਆਲਾ ਜ਼ਿਲ੍ਹਾ, ਪੰਜਾਬ, ਭਾਰਤ',
    'footer.phone': '+91-XXXX-XXXXXX',
    'footer.email': 'info@nabhacare.in',
    'footer.copyright': '© 2025 ਨਾਭਾਕੇਅਰ। ਸਾਰੇ ਹੱਕ ਸੁਰੱਖਿਅਤ। ਕਰੁਣਾ ਅਤੇ ਤਕਨੀਕ ਨਾਲ ਪੇਂਡੂ ਪੰਜਾਬ ਦੀ ਸੇਵਾ।',
    'footer.madeWith': 'ਪੇਂਡੂ ਸਿਹਤ ਸੇਵਾ ਲਈ ❤️ ਨਾਲ ਬਣਾਇਆ ਗਿਆ',

    // Common
    'common.signOut': 'ਸਾਈਨ ਆਉਟ',
    'common.close': 'ਬੰਦ ਕਰੋ',
    'common.save': 'ਸੇਵ ਕਰੋ',
    'common.edit': 'ਸੰਪਾਦਿਤ ਕਰੋ',
    'common.delete': 'ਮਿਟਾਓ',
    'common.view': 'ਦੇਖੋ',
    'common.date': 'ਤਾਰੀਖ',
    'common.time': 'ਸਮਾਂ',
    'common.status': 'ਸਥਿਤੀ',
    'common.scheduled': 'ਨਿਰਧਾਰਿਤ',
    'common.ongoing': 'ਚੱਲ ਰਿਹਾ',
    'common.cancelled': 'ਰੱਦ',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const storageService = StorageService.getInstance();
  
  const [language, setLanguage] = useState<Language>(() => {
    const saved = storageService.getItem('nabhacare_language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    storageService.setItem('nabhacare_language', language);
  }, [language, storageService]);

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};